name: "publish"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set env vars"
        run: |
          echo "GITHUB_SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "${GITHUB_ENV}"

      - name: "Create website resources"
        run: |
          ./manage.sh make_dist -v "${{ env.GITHUB_SHA_SHORT }}"

      - name: "Deploy to GitHub Pages"
        if: "success()"
        uses: "crazy-max/ghaction-github-pages@v2"
        with:
          target_branch: "gh-pages"
          build_dir: "dist"
          commit_message: "Synchronize website to ${{ env.GITHUB_SHA_SHORT }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
